### PR TITLE
Add monochrome icon

### PR DESCRIPTION
**Pull request by txyyh**
Signed-off-by: txyyh <zjh330726@gmail.com>

Implement issue #292 

Eyes removed because I don't know how to draw it just use single color.

Screenshot_20220918-022152_1

### CODE REVIEW

**Comment by machiav3lli** [comment]
Ah thanks! had you ask me, I could've provide you the original SVGs.
Should I merge it like this or you'd like to have the SVGs?

**Comment by txyyh** [comment]
I get the SVG file use VectorDrawable to SVG converter, modified SVG file, then edit XML with reference to modified SVG.
So I do not need origin SVG file.
I can provide modified SVG if you want it.

**Comment by txyyh** [comment]
Screenshot_20220918-091324_Quickstep_1

Updated, now eyes has been added

**Comment by machiav3lli** [comment]
Thanks again for your work. I took a note and will be adding the respective SVG sources of all Neo Applications in the respective repo as this maybe be of use for contributors.

**Comment by txyyh** [comment]
monochrome
Here is the SVG file

**Comment by machiav3lli** [comment]
neo_backup_fg
neo_feed_fg
neo_launcher_fg
neo_wellbeing_fg

Here are the SVGs of the Neo Apps if you'd like to do the same, but no presure if you don't feel to.

**Pull request merged**
