### PR TITLE
Add possibility to install apps with priveliged API

### PR DESCRIPTION
**Pull request by 0x50f13**
Hello.
I have added possibility to install packages without asking user if app installed as privileged.
I also have added `config/` folder which shows example system configuration for integrating app with AOSP.
Sorry in advance for a (bit) messy code :)

I have tested my implementation on eng build of my ROM, though it can be done on any device with root and disable verity for system partition by simply copying debug APK file to `/system/priv-app` and `privapp-permissions-neostore.xml` to `/system/etc/permission`

### CODE REVIEW

**Comment by machiav3lli** [comment]
Thanks much! It would be cool, if you could add it as an option (in `Preferences.kt`) instead of being automatic choice when the permission is available. Eventually some users have their preferences on the installer (e.g. Root or AM).
Thanks again!

**Comment by 0x50f13** [comment]
You are welcome :)
Okay, I would try adding it as an option

**Comment by machiav3lli** [comment]
The implementation seems good. I would be bothering you with one last thing, can you please clean up the strings, the string should be added only to English to allow users to translate all the other languages on Weblate.

**Comment by 0x50f13** [comment]
Okay, I have removed all translations stubs except English

**Comment by machiav3lli** [comment]
Thanks!

**Pull request merged**
